params:
  epochs: 20
  batch_size: 32
  no_classes: 10
  input_shape: [28,28]
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: sgd
  validation_datasize: 5000
  patience: 5
  restore_best_weights: True

artifacts:
  artifacts_dir: artifacts
  model_dir: model 
  plots_dir: plots
  checkpoint_dir: checkpoints
  model_name: model
  plot_name: plots

  
logs:
  logs_dir: logs
  general_logs: general
  tensorboard_logs: tensorboard
